# docker-compose.yml
version: "3"
services:
  backend:
    container_name: backend
    restart: on-failure
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/backend/app/
      - /backend/app/node_modules

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
        - "3001:3001"
    environment:
        PORT: 3001

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
